name: Build And Publish Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


defaults:
  run:
    working-directory: server

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mail-code-server
          path: server/build/libs

      - name: Publish to Dockerhub
        run: ./gradlew publishImage
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
