name: Build Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock
      - name: Build With Yarn
        run: |
          yarn install
          yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mail-code-extension
          path: client/build/chrome-mv3-prod
